initialise the repository
RealDevSquad/reciprocal-backend pull request #1
Opened 2024-09-07 11:29 UTC by yesyash

Date: 

Developer Name: 

---

## Issue Ticket Number

## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-09-07 19:20 UTC, iamitprakash requested changes
readme is not working

2024-09-08 16:15 UTC, yesyash commented
> readme is not working
@iamitprakash added the step to install `air`

2024-09-08 16:25 UTC, iamitprakash approved these changes

2024-09-15 06:14 UTC, prakashchoudhary07 approved these changes

2024-09-15 06:15 UTC, merged